### ISSUE TITLE
Doesn't work with Sapper

### ISSUE THREAD

**Issue by JeffWScott** [heithemmoumni/svelte-spinkit#1]
With basically a [sapper starter template](https://sapper.svelte.dev/) site and using the instructions on th `svelte-spinkit readme` I get this error:

```bash
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'svelte-spinkit'
Require stack:
- /Users/user/Documents/my-app/__sapper__/build/server/server.js
- /Users/user/Documents/my-app/__sapper__/build/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/user/Documents/my-app/__sapper__/build/server/server.js:8:15)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/user/Documents/my-app/__sapper__/build/server/server.js',
    '/Users/user/Documents/my-app/__sapper__/build/index.js'
  ]
}
```

I do see `svelte-spinkit` in both my `package.json` and the `node_modules` folder.  All other modules load fine.

Troubleshooting:
1. delete node_modules folder
2. delete package.json.lock file
3. run `npm install` again

Same error

**Comment by zakaria-chahboun** [comment]
Yes this is an issue but you can use it in client side only (dynamic import) like this:

```svelte
<script>
let spinkit;

onMount(async()=>{
let module = await import("svelte-spinkit");
});
spinkit = module.default;
</script>

<svelte:component bind:this=spinkit name="circle"  ></svelte:component>
```

**Comment by JeffWScott** [comment]
Thx
